policy_type: 'GAIL'
model_path: 'safebench/agent/model_ckpt/GAIL'
model_id: 0
results_folder_path: ''
obs_type: 0

train_episode: 6000
eval_in_train_freq: 1
save_freq: 20
buffer_capacity: 2000
ego_state_dim: 4
ego_action_dim: 2
hidden_dim: 128
lr_d: 0.002
batch_size: 128
lmbda: 0.9

# ppo
clip_epsilon: 0.2
gamma: 0.95
train_iteration: 10   # how many times training
train_interval: 1     # how often training
policy_lr: 1.0e-4
value_lr: 20.0e-4
batch_size: 128
