scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'adv_behavior_single.json'
scenario_category: 'planning'
policy_type: 'ddpg'

route_dir: 'safebench/scenario/scenario_data/route'
scenario_id: 8
route_id: 4

# parameters for agent policy
ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0

# parameters for scenario policy
# for scenario id 1
#scenario_state_dim: 27 # 3*9 - actor number * actor info dim
#scenario_action_dim: 1

# for scenario id 8
scenario_state_dim: 8 # 2*9 - actor number * actor info dim
scenario_action_dim: 1

# for DDPG policy model
model_path: 'safebench/scenario/scenario_data/model_ckpt/ddpg'
model_id: 1
train_episode: 2000
save_freq: 20
eval_in_train_freq: 10
buffer_capacity: 10000
buffer_start_training: 100

actor_lr: 1.0e-4
critic_lr: 1.0e-3
tau: 0.01
update_iteration: 1
gamma: 0.95
epsilon: 0.1  # epsilon greedy
batch_size: 64

