scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'adv_init_state.json'
scenario_category: 'planning'
policy_type: 'GradDescent'

route_dir: 'safebench/scenario/scenario_data/route'
scenario_id: 8
route_id: 4

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0

# for GradDescent policy model
initial_point: [0.5, 0.0]
lr: 0.02
train_episode: 1000
epsilon: 0.08

# useless
buffer_capacity: 100
eval_in_train_freq: 10
save_freq: 40
batch_size: 64


