scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'adv_init_state.json'
scenario_category: 'planning'
policy_type: 'lc'

route_dir: 'safebench/scenario/scenario_data/route'
scenario_id: 8
route_id: 4

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0

# for REINFORCE policy model
model_path: 'safebench/scenario/scenario_data/model_ckpt/lc'
model_id: 1
buffer_capacity: 1000
batch_size: 128
lr: 0.008
eval_in_train_freq: 10
save_freq: 40
train_episode: 2000
itr_per_train: 5
