scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'random.json'
scenario_category: 'planning'
policy_type: 'random'

route_dir: 'safebench/scenario/scenario_data/route'
scenario_id: 8
route_id: 4

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0

model_path: ''
save_freq: 40
