scenario_type_dir: 'safebench/scenario/config/scenario_type'
scenario_type: 'scenic.json'
scenario_category: 'scenic'
policy_type: 'scenic'

route_dir: 'safebench/scenario/scenario_data/route'
scenic_dir: 'safebench/scenario/scenario_data/scenic_data/'
sample_num: 50
opt_step: 10
select_num: 2

method: 'scenic'
scenario_id: null
route_id: [8,9]

ego_action_dim: 2
ego_state_dim: 4
ego_action_limit: 1.0

